title: French RRS Monitor
description: French Rights Retention Strategy Monitor
show_downloads: false
google_analytics: French Right Retention Strategy Monitor
theme: jekyll-theme-cayman
data_update_date: 2022-10-18